version: "3.8"
services:
  tolendar-db:
    image: postgres:14
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: tolendaruser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tolendar
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080